service: ohys-server

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-2

functions:
  app:
    handler: src/serverless.handler
    url: true

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    plugins: build.js
